### ISSUE TITLE
Nitrogen allows empty interface, which doesn't compile

### ISSUE THREAD

**Issue by grabbou** [mrousavy/nitro#123]
```
export interface Open {}

export interface Closed {
  code: string
  reason: string
}

export interface Foo extends HybridObject<{ ios: 'swift' }> {
  create(
    callback: (
      type: string,
      event: Open | Closed
    ) => void
  ): WebSocket
}
```

Error below

<img width="868" alt="Screenshot 2024-09-14 at 16 42 19" src="https://github.com/user-attachments/assets/81d4c6f8-2c7d-4d4e-954a-9f74b3acfa1d">

**Comment by mrousavy** [comment]
Lol, interesting! This is definitely a bug

**Comment by mrousavy** [comment]
I just pushed a commit to main where Nitrogen **throws** if you try to use an empty struct.

But now I decided why not just support it, so I created #212

**Comment by mrousavy** [comment]
"fixed" now, by throwing in nitrogen. empty structs are not supported
