### ISSUE TITLE
Using `protocol` as a property name in spec will result in an error

### ISSUE THREAD

**Issue by grabbou** [mrousavy/nitro#124]
For the spec:
```
export interface Foo {
  protocol: string
}
```

The following generated code:
```
 init(protocol: String) {
    self.init(std.string(protocol))
  }

  var protocol: String {
    @inline(__always)
    get {
      return String(self.__protocol)
    }
    @inline(__always)
    set {
      self.__protocol = std.string(newValue)
    }
  }
}
```
is not correct, obviously haha. I will fix that myself, but perhaps Nitro could throw an error.

**Comment by mrousavy** [comment]
hmm this is a bit tricky since we technically need to escape all keywords of Swift and C++.

Not sure if that's something codegen should do, as that just adds a lot of extra complexity

**Comment by grabbou** [comment]
Yeah, I agree. My suggestion was that codegen could throw an error that this property name is not allowed, like it does for other issues already.
