### ISSUE TITLE
Combining optionals with union doesn't always work

### ISSUE THREAD

**Issue by grabbou** [mrousavy/nitro#125]
For the following signatures:
-  `(event?: Type | TypeB)` 
- `(event: Type | TypeB)`,

Nitrogen will generate enum that are required

I tried to workaround with empty interface, but that doesn't work (see #123)

**Comment by mrousavy** [comment]
Does `event: Type | TypeB | undefined` work?

**Comment by mrousavy** [comment]
Fixed this in https://github.com/mrousavy/nitro/pull/130! :)
