### ISSUE TITLE
Rust Support?

### ISSUE THREAD

**Issue by Jonatthu** [mrousavy/nitro#161]
Just close this issue if this is stupid or impossible.
I was just thinking maybe there is an opportunity to start using rust on really fast modules.

**Comment by mrousavy** [comment]
I think that's something you want to do yourself.

Nitro is fully built with C++, and bridging from C++ to Rust is quite easy I think. 

Btw, performance isn't really a concern here - whether your module is in C++ or Rust probably makes no difference in performance - maybe C++ could even be faster at times.
