### ISSUE TITLE
Nitrogen is not respecting optionals

### ISSUE THREAD

**Issue by jpudysz** [mrousavy/nitro#20]
I can't confirm if this happens for other types, but when I create a function like this:

```ts
//MySpec.nitro.ts
interface MySpec extends HybridObject<{ ios: 'c++', android: 'c++' }> {
 // other fields
 
 
 setRootViewBackgroundColor(hex: string, alpha?: number): void
 // or
 setRootViewBackgroundColor(hex?: string, alpha?: number): void
}
```

The generted cpp type has no `std::optional` and it always looks like this

```cpp
using Func_void_std__string_double = std::function<void(const std::string& /* hex */, double /* alpha */)>;
```

I'm suspecting that this bug might affect the function's arguments

**Comment by mrousavy** [comment]
Heyo - back from my vacation, I finally found a fix for this: https://github.com/mrousavy/nitro/pull/143 :)
