### ISSUE TITLE
Android gradle error "react-native": "0.74.5"

### ISSUE THREAD

**Issue by psquizzle** [mrousavy/nitro#200]
When trying to compile a test library for Android I am getting the following gradle errors. Using react-native 0.74.5. Unresolved References: FastNative and jsCallInvokerHolder.

[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/NitroModules.kt:36:45 Unresolved reference: jsCallInvokerHolder
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/NitroModulesPackage.kt:22:46 None of the following functions can be called with the arguments supplied:
[RUN_GRADLEW] public constructor ReactModuleInfo(p0: String!, p1: String!, p2: Boolean, p3: Boolean, p4: Boolean, p5: Boolean) defined in com.facebook.react.module.model.ReactModuleInfo
[RUN_GRADLEW] public constructor ReactModuleInfo(p0: String!, p1: String!, p2: Boolean, p3: Boolean, p4: Boolean, p5: Boolean, p6: Boolean) defined in com.facebook.react.module.model.ReactModuleInfo
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:6:26 Unresolved reference: optimization
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:34:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:36:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:38:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:41:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:43:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:45:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:47:4 Unresolved reference: FastNative
[RUN_GRADLEW] > Task :react-native-gesture-handler:generateCodegenArtifactsFromSchema
[RUN_GRADLEW] 64 actionable tasks: 64 executed
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:49:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:51:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:53:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:56:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:58:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:60:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:66:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:68:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:70:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:72:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt:74:4 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:6:26 Unresolved reference: optimization
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:79:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:85:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:91:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:97:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:103:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:109:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:115:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:122:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:129:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyValue.kt:136:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/ArrayBuffer.kt:6:26 Unresolved reference: optimization
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/ArrayBuffer.kt:91:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/ArrayBuffer.kt:93:6 Unresolved reference: FastNative
[RUN_GRADLEW] e: file:///private/var/folders/rl/9tgdr27n0nj7lm5mt4t58tr80000gn/T/eas-build-local-nodejs/c208c349-abbb-48e4-a30d-ccb816d1fa19/build/node_modules/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/ArrayBuffer.kt:95:6 Unresolved reference: FastNative
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':react-native-nitro-modules:compileDebugKotlin'.
[RUN_GRADLEW] > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
[RUN_GRADLEW]    > Compilation error. See log for more details
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 40s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.

**Comment by mrousavy** [comment]
Yea you need react-native 0.75+ for Nitro. It uses some newer APIs.

**Comment by mrousavy** [comment]
FastNative is definitely imported in `AnyMap.kt`, so this error might be coming from something else. Either your setup (try in the example app here), or because of RN 0.74. https://github.com/mrousavy/nitro/blob/2e2e67fbeb96efb4fb8bfa779d6ed009d42675d4/packages/react-native-nitro-modules/android/src/main/java/com/margelo/nitro/core/AnyMap.kt#L6

**Comment by psquizzle** [comment]
I am getting the same error now using  "react-native": "0.75.4". The project is essentially the nitro module template with one c++ HostObject. Installing the following into a blank expo app: https://github.com/psquizzle/af-nitro

**Comment by mrousavy** [comment]
1. The template is a template for a "nitro module" - a library for nitro. This is not something that you can run. This is a library, not an app.
2. If you want to run something, you need to create an app (typically an `example` app in such a library). E.g. via create-react-native or Expo.
3. You are missing an import in `FS.nitro.ts` (HybridObject)

**Comment by mrousavy** [comment]
I updated the docs and added [5. Run it](https://nitro.margelo.com/docs/using-nitro-in-a-library#4-run-it) to make it clearer :)

**Comment by psquizzle** [comment]
I am installing this as a library into a new expo app, not trying to build the library as an app. This works perfectly for iOS but the above error occurs when trying to build the app for Android. FS.nitro.ts is placed under /src/specs/.

**Comment by psquizzle** [comment]
Thank you, much appreciated. I just initiated a new project again and the same error occurs when building for android. iOS works as expected:  https://github.com/psquizzle/nitro-android-build-error.git

**Comment by mrousavy** [comment]
The app you shared still uses react-native 0.74.
I think this is because Expo 51 is just tied to RN 0.74.

Your package-lock.json shows that RN 74 was used.

On RN 75, everything should build - see the `example/` app here.

**Comment by psquizzle** [comment]
I use yarn as my package manager the package-lock.json must have been from the original initialisation through create-expo-app

From yarn.lock

react-native@0.75.0:
  version "0.75.0"
  resolved "https://registry.yarnpkg.com/react-native/-/react-native-0.75.0.tgz#10e48d76892fa9404ab9f7a9f22fecf3dfa80ca8"
  integrity sha512-vNNekY0g02uZn1mB6wWXyKhoHvIh9IXqd0Zconh2OImr8zIMVSgTLjilzg8HcfLCwHukTew8R6vvyDUX8NwjvA==
  
  The same error is occurring:
Unresolved reference: optimization
 Unresolved reference: FastNative

running expo prebuild warns of:
✔ Created native directories | reusing /android, /ios
› Using current versions instead of recommended react-native@0.74.5.
✔ Updated package.json | no changes
✔ Finished prebuild

**Comment by psquizzle** [comment]
The issue was that I copied some expo-build properties from another app which forced Android API level 33 and 
dalvik.annotation.optimization.FastNative is available up API level 34. I appreciate your help on this issue and your contributions to the react native community as a whole :).

**Comment by mrousavy** [comment]
nice thanks!

**Comment by mrousavy** [comment]
added it to the minimum requirements section in the Troubleshooting docs!
