### ISSUE TITLE
.nitro.ts content not recognized

### ISSUE THREAD

**Issue by sakarzac000** [mrousavy/nitro#202]
In my app, on 0.11.0, I run nitro-codegen on the example Math spec, and it doesn't find the Spec inside of the file. Downgrading to 0.10.0 works.

**Comment by mrousavy** [comment]
closing for now - if you share the file I might be able to help

**Comment by sakarzac000** [comment]
Here's what I had in my Math.nitro.ts:

interface Math extends HybridObject<{ ios: 'swift', android: 'kotlin' }> {
    readonly pi: number
    add(a: number, b: number): number
}

As shown in example. When running `npm run nitro-codegen`, it recognizes the file exists but says no specs were found in file. Downgraded to 0.10.0 and it worked just fine.

**Comment by mrousavy** [comment]
Did you properly import `HybridObject`?

**Comment by mrousavy** [comment]
Please run nitrogen with `--logLevel="debug"`

**Comment by giovannibedetti** [comment]
I had the same issue, as @mrousavy says `HybridObject` is not being imported. 
Math.nitro.ts content should be:

```
import type { HybridObject } from 'react-native-nitro-modules'

interface Math extends HybridObject<{ ios: 'swift', android: 'kotlin' }> {
  readonly pi: number
  add(a: number, b: number): number
}
```

now running `npx nitro-codegen` correctly generates the project files.
Please update the docs!

**Comment by mrousavy** [comment]
> as [@mrousavy](https://github.com/mrousavy) says `HybridObject` is not being imported. 

Every IDE and TypeScript compiler will tell you that HybridObject is unknown and needs to be imported - it won't compile and is a red line in every case.

I don't think the docs have to show every single import, this is very self explanatory and people will figure out that you need to import that type if it's something Nitro introduces.

> Please update the docs!

To keep the docs simple and avoid having too much code in there, I won't add this. 
Again, the import is self-explanatory and the code sample is weird to copy if it comes along with an import.

Also; the project is OSS
