### ISSUE TITLE
Using `type` yields "Anonymous objects cannot be represented in C++" error

### ISSUE THREAD

**Issue by hannojg** [mrousavy/nitro#222]
### What happened?

Using a nested type in another type which is used in a HyrbidObject spec yields the error bellow.
The documentation + nitrogen indicate that using type should be possible.

When changing `FrameInfo` to be an interface nitrogen can generate a spec!

### Nitrogen CLI logs (with `--logLevel="debug"`)

```tsx
⏳  Parsing Choreographer.nitro.ts...
    ⚙️   Generating specs for HybridObject "Choreographer"...
        ❌  Failed to generate spec for Choreographer! Error: Anonymous objects cannot be represented in C++! Extract "import("/Users/hannomargelo/Documents/Github/react-native-filament/package/src/types/Choreographer.nitro").FrameInfo" to a separate interface/type declaration.
    ❌  No specs found in Choreographer.nitro.ts!
```

### Nitro Specs (`.nitro.ts`)

```ts
export type FrameInfo = {
  /**
   * The current timestamp in nanoseconds.
   */
  timestamp: number
}

export type RenderCallback = (frameInfo: FrameInfo) => void

export interface Choreographer extends PointerHolder {
  addFrameCallbackListener(callback: RenderCallback): Listener
}
```

### Nitro Modules Version

0.11.0

### Nitrogen Version

0.11.0

### Operating system

MacOS

### Additional information

- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/troubleshooting).
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
Not sure if I got it - are you saying `type` fails, but `interface` works?

**Comment by hannojg** [comment]
Yes

**Comment by mrousavy** [comment]
Can you add a simple reproduction case to `TestObject.nitro.ts` in a PR then I can fix it
