### ISSUE TITLE
Invalid `project.podspec` file: no implicit conversion of Array into String.

### ISSUE THREAD

**Issue by fbeccaceci** [mrousavy/nitro#233]
### How were you trying to build the app?

The problem arises when doing pod install.

It shouldn't be nothing hard to fix, i simply noticed that the ruby file generated by nitrogen contains the following

```ruby
spec.source_files = current_source_files + [
    # Generated cross-platform specs
    "nitrogen/generated/shared/**/*.{h,hpp,c,cpp,swift}",
    # Generated bridges for the cross-platform specs
    "nitrogen/generated/ios/**/*.{h,hpp,c,cpp,mm,swift}",
  ]
```

Which cause the error if in my .podspec i have this 
```ruby
s.source_files = "ios/**/*.{h,m,mm,cpp}"
```

So i can easily fix the error by wrapping the sources in my .podspec with braces

```ruby
s.source_files = ["ios/**/*.{h,m,mm,cpp}"]
```

Not a big deal but probably a case that was not considered

### Full build logs

```tsx
[!] Invalid `Podfile` file: 
[!] Invalid `project.podspec` file: no implicit conversion of Array into String.
```

### Project dependencies

```json
"devDepdencies": {
 "react-native": "0.75.4",
 "react-native-nitro-modules": "^0.11.0",
}
```

### Nitro Modules Version

0.11.0

### Nitrogen Version

0.11.0

### Target platforms

iOS

### Operating system

MacOS

### Can you build the Nitro Modules Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I am using Nitrogen (nitro-codegen)
- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/troubleshooting).
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
Fixed in https://github.com/mrousavy/nitro/pull/234 - can you check if that works for you?
