### ISSUE TITLE
SIGABRT on HybridObjectRegistry::registerHybridObjectConstructor on Android

### ISSUE THREAD

**Issue by fbeccaceci** [mrousavy/nitro#254]
### What's happening?

I implemented the nitro module on ios, now i'm moving to the android implementation, i setup the project following the docs and the template in this repo, i can build the app but i get a SIGABRT when trying to use a nitro module.

I noticed the error is caused by this line:
```c++
return JNISharedPtr::make_shared_from_jni<JHybridMapboxNavigationViewManagerRegistrySpec>(globalRef);
```
in MapboxNavigationOnLoad.cpp

in particular is caused by 
```c++
return std::shared_ptr<T>(ref->cthis(), GlobalRefDeleter<T>{ref});
```
in JNISharedPtr.hpp

I found out that calling ref->cthis() causes the SIGABRT but i don't know the reason for that.

### Reproduceable Code

```tsx
I don't know exactly where the problem is but you can here is my repo https://github.com/fbeccaceci/MapboxNavigation
```

### Relevant log output

```shell
Debugger attached to process 4947
Signal: SIGABRT (signal SIGABRT)
killed

Process finished with exit code 9
```

### Device

Android simulator API 34

### Nitro Modules Version

0.11.0

### Nitrogen Version

0.11.0

### Can you reproduce this issue in the Nitro Example app here?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [X] I am using Nitrogen (nitro-codegen)
- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/troubleshooting).
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
I need more log output. The troubleshooting guide tells you how to get those logs

**Comment by fbeccaceci** [comment]
I provided the logs i have, that's the whole console output

Here is the stack trace
<img width="1326" alt="Screenshot 2024-10-23 alle 15 49 11" src="https://github.com/user-attachments/assets/97583dac-22db-4635-9091-d5c585b34906">

This zip contains the logcat output, it is to long to be pasted here
[Pixel-8-Pro-API-34-Android-14_2024-10-23_155352.logcat.zip](https://github.com/user-attachments/files/17492681/Pixel-8-Pro-API-34-Android-14_2024-10-23_155352.logcat.zip)

I think the most relevant part in the logcat logs is
```
java_vm_ext.cc:591] JNI DETECTED ERROR IN APPLICATION: attempt to access field com.facebook.jni.HybridData com.margelo.nitro.com.mapboxnavigation.HybridMapboxNavigationViewManagerRegistrySpec.mHybridData from an object argument of type com.margelo.nitro.com.mapboxnavigation.HybridMapboxNavigationViewManagerRegistry: 0x61
                                                                                                    java_vm_ext.cc:591]     in call to GetObjectField
                                                                                                    java_vm_ext.cc:591]     from void com.facebook.jni.NativeRunnable.run()
```

Can you reopen this?

**Comment by fbeccaceci** [comment]
I'm sorry, i'm stupid i was extending the wrong class in kotlin

**Comment by mrousavy** [comment]
ah no worries - well that's somethign i can maybe also explicitly check for (in debug)
