### ISSUE TITLE
Add react-native-nitro-modules to peerDependencies in example/package.json

### ISSUE THREAD

**Issue by jobpaardekooper** [mrousavy/nitro#359]
### What's happening?

I am wondering if there is a reason why in the [example/package.json](https://github.com/mrousavy/nitro/blob/main/example/package.json) file the `react-native-nitro-modules` is not added as a peer dependency. To me it seems from [the nitro docs](https://nitro.margelo.com/docs/for-users) that library users will always need to install this package so might as well add it as a peer dependency. Or am I missing something?

I know it's a small thing, just curious if there is a reason not to do it.

### Reproduceable Code

```tsx
-
```

### Relevant log output

```shell
-
```

### Device

-

### Nitro Modules Version

0.17.0

### Nitrogen Version

0.17.0

### Can you reproduce this issue in the Nitro Example app here?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [X] I am using Nitrogen (nitro-codegen)
- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
- [ ] I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
1. The `example/` is not an example library - it is an example app. The example librars is in `packages/react-native-nitro-image`.
2. The deps in the example app should be in `dependencies`, not `devDependencies`. Thanks for reminding me - I just fixed that.

**Comment by jobpaardekooper** [comment]
Sorry, I was looking at the wrong directory when writing the issue. I ment to refer to [`packages/template/package.json`](https://github.com/mrousavy/nitro/blob/main/packages/template/package.json). There `react-native-nitro-modules` is not in the `peerDependencies`. And this is the template library that the documentations also suggests to copy to get started. For `packages/react-native-nitro-image` it is correctly listed in the `peerDependencies` but not for `packages/template`.

**Comment by mrousavy** [comment]
Ah you are correct!!
