### ISSUE TITLE
Variant (`A | B | C`) doesn't work in Swift

### ISSUE THREAD

**Issue by mrousavy** [mrousavy/nitro#39]
When creating a variant (union) type, the Swift code gets generated but it won't compile.

Tuple:

```ts
interface MyHybrid extends HybridObject<{ ios: 'swift' }> {
  someFunc(value: number | string): void
}
```

Generated Swift:

```swift
class MyHybrid implements MyHybridSpec {
  func someFunc(value: Variant_Double_String) {
    // do nothing
  }
}
```

Looks good, but unfortunately it will fail to compile because the Swift compiler inserted an additional `<` and `>` around the C++ type (`std::variant<<...>>` instead of `std:: variant<..>`) in the generated `-Swift.h` header:

```diff
- SWIFT_INLINE_THUNK std::__1::variant<<std::string, double>> MyHybridSpecCxx::getSomeVariant() {
```

I already reported this bug in the Swift compiler repo: https://github.com/swiftlang/swift/issues/75865

Until that's fixed, variants/unions are currently not supported in Nitrogen.

**Comment by baronha** [comment]
Still error @mrousavy 
My code: 
```
export type SelectMode = 'single' | 'multiple'

export interface Options {
    selectMode?: SelectMode
}
```
This causes an error:

<img width="299" alt="Screenshot 2024-10-22 at 16 09 04" src="https://github.com/user-attachments/assets/f26a4f54-2aeb-4570-99f8-4c3fc71ab8ee">

And if it's not Optional, it works normally:
```
export interface Options {
    selectMode: SelectMode // -> Work
}
```

**Comment by mrousavy** [comment]
I just explicitly tested this in Swift, C++ and Kotlin and it compiles fine: https://github.com/mrousavy/nitro/pull/253

**Comment by mrousavy** [comment]
@baronha

**Comment by baronha** [comment]
> @baronha

OMG. my mistake for not using it:
```
export interface Options extends HybridObject<{ android: 'kotlin'; ios: 'swift' }> {}
```

**Comment by mrousavy** [comment]
No idea. Those are not full build logs.
Please read [the Troubleshooting guide](https://nitro.margelo.com/docs/troubleshooting) to find out how to post full build logs.

Also, again; it works here on main. Exactly what you posted. Maybe there is some difference in your API :)
