### ISSUE TITLE
error: no member named 'toCpp' on Android

### ISSUE THREAD

**Issue by baronha** [mrousavy/nitro#448]
### What's happening?

I don't know if this is valid? but when I declare a callback function in the config this in iOS works great. But building on Android has an error due to missing `toCpp()`
![Screenshot 2024-12-25 at 10 31 12](https://github.com/user-attachments/assets/19495de6-8690-40da-9d59-5073a46b88ad)

### Reproduceable Code

```tsx
import { type HybridObject } from 'react-native-nitro-modules'

export type NitroPreviewConfig = {
  language: Language

  /**
   * Auto play video when open preview.
   *
   * @platform iOS, Android
   */
  videoAutoPlay?: boolean

  onLongPress?: (index: number) => void // --> THIS FUNC
}

export interface MultipleImagePicker
  extends HybridObject<{ ios: 'swift'; android: 'kotlin' }> {
  openPreview(
    media: MediaPreview[],
    index: number,
    config: NitroPreviewConfig
  ): void
}
```

### Relevant log output

```shell
/Users/mac/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android24 --sysroot=/Users/mac/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -DMultipleImagePicker_EXPORTS -I/Users/mac/project/react-native-multiple-image-picker/android/../nitrogen/generated/shared/c++ -I/Users/mac/project/react-native-multiple-image-picker/android/../nitrogen/generated/android/c++ -I/Users/mac/project/react-native-multiple-image-picker/android/../nitrogen/generated/android -I/Users/mac/project/react-native-multiple-image-picker/android/src/main/cpp -I/Users/mac/project/react-native-multiple-image-picker/android/../cpp -isystem /Users/mac/.gradle/caches/8.10.2/transforms/d31f451122629a882eaa4d4e39fe5824/transformed/fbjni-0.6.0/prefab/modules/fbjni/include -isystem /Users/mac/.gradle/caches/8.10.2/transforms/09e99889bdbc3a72b28a5d49d1ebcf4c/transformed/react-android-0.76.5-debug/prefab/modules/jsi/include -isystem /Users/mac/project/react-native-multiple-image-picker/example/node_modules/react-native-nitro-modules/android/build/headers/nitromodules -isystem /Users/mac/.gradle/caches/8.10.2/transforms/09e99889bdbc3a72b28a5d49d1ebcf4c/transformed/react-android-0.76.5-debug/prefab/modules/reactnative/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O2 -frtti -fexceptions -Wall -fstack-protector-all -fno-limit-debug-info  -fPIC -std=gnu++20 -MD -MT CMakeFiles/MultipleImagePicker.dir/Users/mac/project/react-native-multiple-image-picker/nitrogen/generated/android/c++/JHybridMultipleImagePickerSpec.cpp.o -MF CMakeFiles/MultipleImagePicker.dir/Users/mac/project/react-native-multiple-image-picker/nitrogen/generated/android/c++/JHybridMultipleImagePickerSpec.cpp.o.d -o CMakeFiles/MultipleImagePicker.dir/Users/mac/project/react-native-multiple-image-picker/nitrogen/generated/android/c++/JHybridMultipleImagePickerSpec.cpp.o -c /Users/mac/project/react-native-multiple-image-picker/nitrogen/generated/android/c++/JHybridMultipleImagePickerSpec.cpp

In file included from /Users/mac/project/react-native-multiple-image-picker/nitrogen/generated/android/c++/JHybridMultipleImagePickerSpec.cpp:93:
/Users/mac/project/react-native-multiple-image-picker/android/../nitrogen/generated/android/c++/JNitroPreviewConfig.hpp:46:66: error: no member named 'toCpp' in 'facebook::jni::HybridClass<margelo::nitro::multipleimagepicker::JFunc_void_double>::JavaPart'
        onLongPress != nullptr ? std::make_optional(onLongPress->toCpp()) : std::nullopt
                                                    ~~~~~~~~~~~~~^
```

### Device

Emulator Android

### Nitro Modules Version

0.20.1

### Nitrogen Version

0.20.1

### Can you reproduce this issue in the Nitro Example app here?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [X] I am using Nitrogen (nitro-codegen)
- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
- [ ] I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
fix: https://github.com/mrousavy/nitro/pull/453

**Comment by mrousavy** [comment]
Unrelated to this being a bug, it is recommended to avoid objects if you can: 
![image](https://github.com/user-attachments/assets/4f9bfb78-94eb-4a39-9dac-cb3687da5beb)

> See [Avoid unnecessary objects](https://nitro.margelo.com/docs/performance-tips#avoid-unnecessary-objects)

**Comment by baronha** [comment]
> Unrelated to this being a bug, it is recommended to avoid objects if you can: ![image](https://private-user-images.githubusercontent.com/15199031/399286647-4f9bfb78-94eb-4a39-9dac-cb3687da5beb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1ODEzMzYsIm5iZiI6MTczNTU4MTAzNiwicGF0aCI6Ii8xNTE5OTAzMS8zOTkyODY2NDctNGY5YmZiNzgtOTRlYi00YTM5LTlkYWMtY2IzNjg3ZGE1YmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE3NTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMDc1MTBmMGE2MjVhYjg1Y2MwOTRmMGVhM2I5N2MyNWMyYWNkZjlmMWFkN2FhODFiNDkyZjczNjBhNGUxNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t8XXJl-50V0AkNX17uGPy_fPR2W0jn8rvlsF5CfqvgQ)
> 
> > See [Avoid unnecessary objects](https://nitro.margelo.com/docs/performance-tips#avoid-unnecessary-objects)

Yah Sir. I followed your instructions to be safer. Thank you for listening to me
