### ISSUE TITLE
Nitrogen creates incorrect paths for Cmake files on Windows

### ISSUE THREAD

**Issue by fax1ty** [mrousavy/nitro#450]
### What's happening?

I tried to run a Gradle sync in Windows using Android Studio, but the process failed

### Reproduceable Code

```tsx
Just run the `specs` script from the template
```

### Relevant log output

```shell
https://discord.com/channels/1147256486762913884/1284173514051555378/1321535265294127136
```

### Device

Android Studio

### Nitro Modules Version

0.20.1

### Nitrogen Version

0.20.1

### Can you reproduce this issue in the Nitro Example app here?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [X] I am using Nitrogen (nitro-codegen)
- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
- [ ] I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
fixed by https://github.com/mrousavy/nitro/pull/451

**Comment by mrousavy** [comment]
btw;

1. wrong issue template (there is a nitrogen template)
2. logs need to be shared regardless. the discord link won't be enough in the future.
